name: Insider LOAD Test Cases

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: PerfAction for JMeter
          uses: QAInsights/PerfAction@v3.1
          with:
            test-plan-path: './n11LoadTest.jmx'
        - name: Upload reports
          uses: actions/upload-artifact@v2
          with:
            name: jmeter-report
            path: result.jtl

            
